In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
## brand = categorical - Nominal
## km_driven = numerical
## fuel = categorical - Nominal
## owner = categorical - Ordinal
# selling price = numerical

In [5]:
df.fuel.value_counts()

Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: fuel, dtype: int64

In [6]:
df.owner.value_counts()

First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: owner, dtype: int64

In [7]:
pd.get_dummies(df,columns=['fuel','owner'], drop_first=True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [9]:
X_train.head()

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [12]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [13]:
X_train_new.shape

(6502, 7)

In [14]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [15]:
flowers = pd.DataFrame({
    'color' : ['red', 'green', 'red', 'green', 'red', 'green', 'red', 'green', 'blue', 'blue'],
    'height': [4,9,4,8,4,7,4,7.5,20,19],
    'petals': [3,9,1,8,1,10,2,8,50,47],
    'days'  : [6,16,7,15,8,17,5,12,40,45]
})
flowers

color  height  petals  days
0    red     4.0       3     6
1  green     9.0       9    16
2    red     4.0       1     7
3  green     8.0       8    15
4    red     4.0       1     8
5  green     7.0      10    17
6    red     4.0       2     5
7  green     7.5       8    12
8   blue    20.0      50    40
9   blue    19.0      47    45

In [16]:
from sklearn.model_selection import train_test_split


In [23]:
X_train, X_test, y_train, y_test = train_test_split(flowers.drop('days', axis=1), flowers['days'],
                                                    test_size=.2, random_state=40)

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
ohe =OneHotEncoder(sparse=False)

In [26]:
ohe.fit(X_train[['color']])

OneHotEncoder(sparse=False)

In [27]:
ohe.transform(X_train[['color']])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
flowers_new = pd.DataFrame({
    'color' : ['red', 'green', 'red', 'pink', 'red', 'green', 'red', 'green', 'blue', 'blue'],
    'height': [4,9,4,8,4,7,4,7.5,20,19],
    'petals': [3,9,1,8,1,10,2,8,50,47],
    'days'  : [6,16,7,15,8,17,5,12,40,45]
})
flowers_new

color  height  petals  days
0    red     4.0       3     6
1  green     9.0       9    16
2    red     4.0       1     7
3   pink     8.0       8    15
4    red     4.0       1     8
5  green     7.0      10    17
6    red     4.0       2     5
7  green     7.5       8    12
8   blue    20.0      50    40
9   blue    19.0      47    45

In [30]:
X_1, X_2, y_1, y_2 = train_test_split(flowers_new.drop('days',axis=1), flowers_new['days'],
                                                    test_size=.2, random_state=40)

In [43]:
enc1 = OneHotEncoder(sparse=False)

In [44]:
X_1['color']

8     blue
1    green
2      red
9     blue
0      red
5    green
7    green
6      red
Name: color, dtype: object

In [45]:
X_2

color  height  petals
4   red     4.0       1
3  pink     8.0       8

In [46]:
enc1.fit_transform(X_1[['color']])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
enc1.transform(X_2[['color']])

ValueError: Found unknown categories ['pink'] in column 0 during transform

In [56]:
enc2 = OneHotEncoder(sparse=False,drop='first',handle_unknown='error')

In [57]:
X_1['color']

8     blue
1    green
2      red
9     blue
0      red
5    green
7    green
6      red
Name: color, dtype: object

In [58]:
enc2.fit_transform(X_1[['color']])

array([[0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [59]:
enc2.transform(X_2[['color']])

ValueError: Found unknown categories ['pink'] in column 0 during transform